name: CI

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  CARGO_TERM_COLOR: always
  DISCORD_TOKEN: ''
  TEST_GUILD_ID: ''
  DATABASE_URL: postgres://postgres:password@localhost:5432/bloom
  OPENAI_API_KEY: ''

jobs:
  test:
    services:
      postgres:
        image: pgvector/pgvector:pg17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust toolchain installation
        run: rustup toolchain install stable --profile minimal --no-self-update
      - name: Caching setup
        uses: Swatinem/rust-cache@v2
      - name: Checks
        run: cargo check
      - name: Formatting
        run: cargo fmt --all -- --check
      - name: Tests
        run: cargo test --all-features
      - name: Clippy
        run: cargo clippy --all --all-features --tests -- -D warnings
